apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
  namespace: default
spec:
  replicas: 50
  selector:
    matchLabels:
      app: microbot
  template:
    metadata:
      name: microbot
      labels:
        app: microbot
    spec:
      containers:
      - name: microbot
        image: cdkbot/microbot:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
