apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: dev.tenefic.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microbot
            port:
              number: 80
  tls:
  - hosts:
    - dev.tenefic.com
    secretName: landing-page-ingress-tls