apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatar
  namespace: game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avatar
  template:
    metadata:
      name: avatar
      labels:
        app: avatar
    spec:
      containers:
      - name: microbot
        image: trungkenbi/avatar:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 19128
