apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunny-town-server
  namespace: games
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sunny-town-server
  template:
    metadata:
      name: sunny-town-server
      labels:
        app: sunny-town-server
    spec:
      containers:
      - name: sunny-town-server
        image: trungkenbi/avatar:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "100m"
        ports:
          - containerPort: 19128
