apiVersion: v1
kind: Service
metadata:
  name: sunny-town-server
  namespace: games
spec:
  type: NodePort
  selector:
    app: sunny-town-server
  ports:
    - port: 19128
      targetPort: 19128
      nodePort: 31905